package starshipfights.game

val ShipType.armaments: ShipArmaments
	get() = when (this) {
		ShipType.BLITZ -> mechyrdiaShipWeapons(1, false, 1, 0, 0, 0)
		ShipType.GLADIUS -> mechyrdiaShipWeapons(2, false, 1, 0, 0, 1)
		ShipType.PILUM -> mechyrdiaShipWeapons(2, false, 0, 1, 0, 1)
		ShipType.SICA -> mechyrdiaShipWeapons(2, false, 0, 0, 1, 1)
		ShipType.KAISERSWELT -> mechyrdiaShipWeapons(2, false, 2, 0, 0, 0)
		ShipType.KAROLINA -> mechyrdiaShipWeapons(2, false, 0, 1, 1, 0)
		ShipType.KOZACHNIA -> mechyrdiaShipWeapons(2, false, 1, 0, 1, 0)
		ShipType.MONT_IMPERIAL -> mechyrdiaShipWeapons(2, false, 0, 2, 0, 0)
		ShipType.MUNDUS_CAESARIS_DIVI -> mechyrdiaShipWeapons(0, true, 2, 0, 0, 0)
		ShipType.VENSCA -> mechyrdiaShipWeapons(2, false, 1, 1, 0, 0)
		ShipType.AUCTORITAS -> mechyrdiaShipWeapons(3, false, 1, 1, 0, 2)
		ShipType.CIVITAS -> mechyrdiaShipWeapons(3, false, 1, 0, 1, 2)
		ShipType.HONOS -> mechyrdiaShipWeapons(0, true, 1, 0, 1, 2)
		ShipType.IMPERIUM -> mechyrdiaShipWeapons(3, false, 0, 0, 2, 2)
		ShipType.PAX -> mechyrdiaShipWeapons(3, false, 2, 0, 0, 2)
		ShipType.PIETAS -> mechyrdiaShipWeapons(0, true, 2, 0, 0, 2)
		ShipType.EARTH -> mechyrdiaShipWeapons(3, false, 1, 1, 1, 1)
		ShipType.LANGUAVARTH -> mechyrdiaShipWeapons(3, false, 1, 2, 0, 1)
		ShipType.MECHYRDIA -> mechyrdiaShipWeapons(3, false, 3, 0, 0, 1)
		ShipType.NOVA_ROMA -> mechyrdiaShipWeapons(3, false, 0, 3, 0, 1)
		ShipType.TYLA -> mechyrdiaShipWeapons(3, false, 1, 0, 2, 1)
		
		ShipType.JAGER -> ndrcShipWeapons(2, true, 0, false, 0, 2)
		ShipType.STER -> ndrcShipWeapons(0, true, 2, true, 3, 0)
		ShipType.ZWAARD -> ndrcShipWeapons(2, false, 2, true, 3, 0)
		ShipType.SLAGSCHIP -> ndrcShipWeapons(3, false, 2, true, 5, 0)
		ShipType.VOORHOEDE -> ndrcShipWeapons(3, true, 0, false, 3, 1)
		ShipType.KRIJGSCHUIT -> ndrcShipWeapons(4, true, 2, true, 6, 0)
		
		ShipType.ERIS -> diadochiShipWeapons(2, false, 1, 0, 0, 0)
		ShipType.TYPHON -> diadochiShipWeapons(0, false, 1, 0, 0, 1)
		ShipType.AHRIMAN -> diadochiShipWeapons(1, false, 0, 1, 0, 0)
		ShipType.APOPHIS -> diadochiShipWeapons(1, false, 0, 0, 1, 1)
		ShipType.AZATHOTH -> diadochiShipWeapons(1, false, 1, 0, 0, 0)
		ShipType.CHERNOBOG -> diadochiShipWeapons(2, false, 0, 2, 0, 0)
		ShipType.CIPACTLI -> diadochiShipWeapons(2, false, 2, 0, 0, 0)
		ShipType.LOTAN -> diadochiShipWeapons(2, false, 0, 0, 2, 2)
		ShipType.MORGOTH -> diadochiShipWeapons(2, false, 1, 1, 0, 0)
		ShipType.TIAMAT -> diadochiShipWeapons(2, false, 1, 0, 1, 1)
		ShipType.CHARYBDIS -> diadochiShipWeapons(3, false, 3, 0, 0, 0)
		ShipType.SCYLLA -> diadochiShipWeapons(3, false, 1, 0, 2, 0)
		ShipType.AEDON -> diadochiShipWeapons(0, true, 3, 0, 0, 0)
		
		ShipType.GANNAN -> fulkreykkShipWeapons(0, true, 0, 0)
		ShipType.LODOVIK -> fulkreykkShipWeapons(4, false, 0, 0)
		ShipType.KARNAS -> fulkreykkShipWeapons(1, false, 2, 0)
		ShipType.PERTONA -> fulkreykkShipWeapons(1, false, 1, 1)
		ShipType.VOSS -> fulkreykkShipWeapons(1, false, 0, 2)
		ShipType.BREKORYN -> fulkreykkShipWeapons(2, false, 2, 0)
		ShipType.FALK -> fulkreykkShipWeapons(0, true, 1, 1)
		ShipType.LORUS -> fulkreykkShipWeapons(0, true, 2, 0)
		ShipType.ORSH -> fulkreykkShipWeapons(2, false, 0, 2)
		ShipType.TEFRAN -> fulkreykkShipWeapons(2, false, 1, 1)
		ShipType.KASSCK -> fulkreykkShipWeapons(3, false, 3, 0)
		ShipType.KHORR -> fulkreykkShipWeapons(3, false, 1, 2)
		
		ShipType.COLEMAN -> vestigiumShipWeapons(4, 0, 1, 1, 0)
		ShipType.JEFFERSON -> vestigiumShipWeapons(4, 0, 0, 1, 1)
		ShipType.QUENNEY -> vestigiumShipWeapons(4, 0, 0, 0, 2)
		ShipType.ROOSEVELT -> vestigiumShipWeapons(4, 0, 0, 2, 0)
		ShipType.WASHINGTON -> vestigiumShipWeapons(4, 0, 3, 0, 0)
		ShipType.ARLINGTON -> vestigiumShipWeapons(7, 0, 1, 0, 0)
		ShipType.CONCORD -> vestigiumShipWeapons(7, 0, 0, 0, 1)
		ShipType.LEXINGTON -> vestigiumShipWeapons(7, 0, 0, 1, 0)
		ShipType.RAVEN_ROCK -> vestigiumShipWeapons(1, 4, 0, 1, 0)
		ShipType.IOWA -> vestigiumShipWeapons(9, 0, 0, 2, 0)
		ShipType.MARYLAND -> vestigiumShipWeapons(3, 4, 0, 2, 0)
		ShipType.NEW_YORK -> vestigiumShipWeapons(0, 6, 0, 0, 2)
		ShipType.OHIO -> vestigiumShipWeapons(9, 0, 3, 0, 0)
	}
